server:
  port: 12900
  compression:
    enabled: true
    mime-types: application/wasm, application/octet-stream
    min-response-size: 3000
spring:
  jpa:
    hibernate:
      ddl-auto: update




  profiles:
    active: prod



thymeleaf:
  prefix: classpath:/templates
  suffix: .html


